# Generated by Django 5.2 on 2025-05-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='usert',
            new_name='creator',
        ),
    ]
